services:
  lazytainer:
    container_name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      VERBOSE: false
    ports:
      - 25565:25565
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    labels:
      - "lazytainer.group.minecraft.sleepMethod=stop"
      - "lazytainer.group.minecraft.ports=25565,19132,19133"
      - "lazytainer.group.minecraft.minPacketThreshold=2"
      - "lazytainer.group.minecraft.inactiveTimeout=600"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: no

  mc:
    image: itzg/minecraft-server:latest
    container_name: "minecraft_server"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      # MEMORY: "3072M"
      MAX_PLAYERS: "15"
      MOTD: "Goofy Ahh server. Thank Hetzner for cheap VPS."
      ONLINE_MODE: "false"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Asia/Kolkata"
      DIFFICULTY: "2"
      VIEW_DISTANCE: "14"
      PLUGINS: |-
        https://hangarcdn.papermc.io/plugins/CyntrixAlgorithm/DeathChest/versions/2.2.8/PAPER/deathchest.jar
        https://hangarcdn.papermc.io/plugins/other/DirectionHUD/versions/1.8.1.2%2B1.21.7/PAPER/directionhud-paper-1.8.1.2%2B1.21.7.jar
        https://hangarcdn.papermc.io/plugins/Black1_TV/Passky/versions/3.3.0/PAPER/Passky-3.3.0.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.2/PAPER/ViaVersion-5.4.2.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.4.2/PAPER/ViaBackwards-5.4.2.jar
        https://download.geysermc.org/v2/projects/geyser/versions/2.8.3/builds/921/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage -1
    volumes:
      - "./data:/data"
    labels:
      - "lazytainer.group=minecraft"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - lazytainer
    network_mode: service:lazytainer
    restart: no
