services:
  web:
    image: ghcr.io/zeecka/aperisolve:latest
    #build: .
    container_name: aperisolve-web
    restart: no
    expose:
      - "5000"
    volumes:
      - apresults:/aperisolve/results
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      worker:
        condition: service_started
    env_file:
      - .env
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.aperisolve.rule=Host(`aperisolve.pranaovs.me`)"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.services.aperisolve.loadbalancer.server.port=5000"
      - "traefik.http.routers.aperisolve.entrypoints=websecure"
      # AutoKuma (uptime-kuma)
      - "kuma.aperisolve_grp.group.name=Aperisolve"
      - 'kuma.aperisolve_grp.group.notification_name_list=["ntfy"]'
      - "kuma.aperisolve_grp.group.parent_name=ctf_grp"
      - "kuma.aperisolve_http.http.name=Aperisolve HTTP"
      - "kuma.aperisolve_http.http.url=https://aperisolve.pranaovs.me"
      - "kuma.aperisolve_http.http.parent_name=aperisolve_grp"
      - "kuma.aperisolve_container.docker.name=Aperisolve Container"
      - "kuma.aperisolve_container.docker.docker_container=aperisolve-web"
      - "kuma.aperisolve_container.docker.docker_host_name=local"
      - "kuma.aperisolve_container.docker.parent_name=aperisolve_grp"
    networks:
      - default
      - traefik_net

  worker:
    image: ghcr.io/zeecka/aperisolve:latest
    #build: .
    container_name: aperisolve-worker
    restart: no
    command: rq worker default --url redis://redis:6379/0
    volumes:
      - apresults:/aperisolve/results
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    container_name: postgres
    restart: no
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aperiuser -d aperisolve"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    restart: no
    env_file:
      - .env

  rqdashboard:
    image: eoranged/rq-dashboard
    container_name: rq-dashboard
    restart: no
    expose:
      - "9181"
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  apresults:
  pgdata:

networks:
  traefik_net:
    external: true
