services:
  fmd:
    # Use the prebuilt image
    image: registry.gitlab.com/fmd-foss/fmd-server:latest
    # build: https://gitlab.com/fmd-foss/fmd-server.git#v0.12.0
    container_name: fmd
    user: "1000:1000"
    volumes:
      - "./data/db:/var/lib/fmd-server/db/"
      - "./data/config.yml:/etc/fmd-server/config.yml"
    environment:
      FMD_REGISTATIONTOKEN: ${REGISTRATIONTOKEN}
    restart: always

networks:
  default:
    name: caddy_net
    external: true
