services:
  fmd:
    # Use the prebuilt image
    image: registry.gitlab.com/fmd-foss/fmd-server:latest
    # build: https://gitlab.com/fmd-foss/fmd-server.git#v0.12.0
    container_name: fmd
    user: "1000:1000"
    volumes:
      - ./data/db:/var/lib/fmd-server/db:Z,U
      - ./data/config.yml:/etc/fmd-server/config.yml:ro,Z,U
    environment:
      FMD_REGISTATIONTOKEN: ${REGISTRATIONTOKEN}
    restart: always
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.fmd.rule=Host(`fmd.pranaovs.me`)"
      - "traefik.http.services.fmd.loadbalancer.server.port=8080"
      - "traefik.http.routers.fmd.entrypoints=websecure"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_net

  autokuma:
    image: busybox:latest
    container_name: fmd-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.fmd_grp.group.name=FMD"
      - 'kuma.fmd_grp.group.notification_name_list=["ntfy"]'
      - "kuma.fmd_http.http.name=FMD HTTP"
      - "kuma.fmd_http.http.url=https://fmd.pranaovs.me"
      - "kuma.fmd_http.http.parent_name=fmd_grp"
      - "kuma.fmd_container.docker.name=FMD Container"
      - "kuma.fmd_container.docker.docker_container=fmd"
      - "kuma.fmd_container.docker.docker_host_name=local"
      - "kuma.fmd_container.docker.parent_name=fmd_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik_net:
    external: true
