services:
  fmd:
    # Use the prebuilt image
    image: registry.gitlab.com/fmd-foss/fmd-server:latest
    # build: https://gitlab.com/fmd-foss/fmd-server.git#v0.12.0
    container_name: fmd
    user: root
    volumes:
      - ./data/db:/var/lib/fmd-server/db:Z,U
      - ./config:/etc/fmd-server:Z,U
    environment:
      FMD_REGISTATIONTOKEN: ${REGISTRATIONTOKEN}
    restart: always
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.fmd.rule=Host(`fmd.pranaovs.me`)"
      - "traefik.http.services.fmd.loadbalancer.server.port=8080"
      - "traefik.http.routers.fmd.entrypoints=websecure"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
