services:
  ittools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: ittools
    restart: always
    expose:
      - "80"
    labels:
      # Traefik
      - "traefik.http.routers.ittools-ts.rule=Host(`ittools.devserver.ts.net`) || Host(`it-tools.devserver.ts.net`) || Host(`ittools.devserver`) || Host(`it-tools.devserver`)"
      - "headnscale.subdomain=ittools|it-tools"
      - "traefik.http.routers.ittools-ts.entrypoints=web"
      - "traefik.http.routers.ittools-ts.service=ittools"

      - "traefik.http.services.ittools.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"
    networks:
      - traefik_net

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: ittools-anubis
    restart: always
    expose:
      - "8923"
    environment:
      BIND: ":8923"
      SLOG_LEVEL: "WARN"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://ittools"
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      COOKIE_DOMAIN: pranaovs.me
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    volumes:
      - ../traefik/config/anubis/anubis.yaml:/data/cfg/botPolicy.yaml:ro,z

    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.ittools-https.rule=Host(`ittools.pranaovs.me`) || Host(`it-tools.pranaovs.me`)"
      - "traefik.http.routers.ittools-https.entrypoints=websecure"
      - "traefik.http.routers.ittools-https.service=ittools-anubis"

      - "traefik.http.services.ittools-anubis.loadbalancer.server.port=8923"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
