services:
  web:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: ittools
    restart: always
    expose:
      - "80"
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.ittools-https.rule=Host(`ittools.pranaovs.me`) || Host(`it-tools.pranaovs.me`)"
      - "traefik.http.routers.ittools-https.entrypoints=websecure"
      - "traefik.http.routers.ittools-https.service=ittools"

      - "traefik.http.routers.ittools-ts.rule=Host(`ittools.devserver.ts.net`) || Host(`it-tools.devserver.ts.net`) || Host(`ittools.devserver`) || Host(`it-tools.devserver`)"
      - "headnscale.subdomain=ittools|it-tools"
      - "traefik.http.routers.ittools-ts.entrypoints=web"
      - "traefik.http.routers.ittools-ts.service=ittools"

      - "traefik.http.services.ittools.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
