services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "30088:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      # For tailscale access
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      # Reverse proxy trusts
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_AUTH_TRUST_PROXY=true
      # Set hostnames
      - N8N_TRUSTED_PROXIES=0.0.0.0/0
      - N8N_HOST=n8n.pranavs.me
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.pranaovs.me/
      - N8N_PROXY_HOPS=1
    env_file: ".env"
    volumes:
      - ./n8n_data:/root/.n8n
    user: root
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.pranaovs.me`) || Host(`n8n.deepanalve.dev`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=le"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
