services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "30088:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      # For tailscale access
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      # Reverse proxy trusts
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_AUTH_TRUST_PROXY=true
      # Set hostnames
      - N8N_TRUSTED_PROXIES=0.0.0.0/0
      - N8N_HOST=n8n.pranaovs.me
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.pranaovs.me/
      - N8N_PROXY_HOPS=1
    env_file: ".env"
    volumes:
      - ./n8n_data:/root/.n8n
    user: root
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.pranaovs.me`) || Host(`n8n.deepanalve.dev`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.middlewares=anubis@docker"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_net

  autokuma:
    image: busybox:latest
    container_name: n8n-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.n8n_grp.group.name=n8n"
      - 'kuma.n8n_grp.group.notification_name_list=["ntfy"]'
      - "kuma.n8n_http_1.http.name=n8n (n8n.pranaovs.me)"
      - "kuma.n8n_http_1.http.url=https://n8n.pranaovs.me"
      - "kuma.n8n_http_1.http.parent_name=n8n_grp"
      - "kuma.n8n_http_2.http.name=n8n (n8n.deepanalve.dev)"
      - "kuma.n8n_http_2.http.url=https://n8n.deepanalve.dev"
      - "kuma.n8n_http_2.http.parent_name=n8n_grp"
      - "kuma.n8n_container.docker.name=n8n Container"
      - "kuma.n8n_container.docker.docker_container=n8n-n8n-1"
      - "kuma.n8n_container.docker.docker_host_name=local"
      - "kuma.n8n_container.docker.parent_name=n8n_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik_net:
    external: true
