services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    user: root
    ports:
      - "30088:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      # For tailscale access
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      # Reverse proxy trusts
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_AUTH_TRUST_PROXY=true
      # Set hostnames
      - N8N_TRUSTED_PROXIES=0.0.0.0/0
      - N8N_HOST=n8n.pranaovs.me
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.pranaovs.me/
      - N8N_PROXY_HOPS=1
    env_file: ".env"
    volumes:
      - ./n8n_data:/home/node/.n8n:Z,U
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.pranaovs.me`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.middlewares=anubis@docker"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
