services:
  bentopdf:
    image: bentopdf/bentopdf-simple:latest
    container_name: bentopdf
    ports:
      - "30085:8080"
    restart: always
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf-https.rule=Host(`pdftools.pranaovs.me`) || Host(`pdf.pranaovs.me`) || Host(`bentopdf.pranaovs.me`)"
      - "traefik.http.routers.bentopdf-https.entrypoints=websecure"
      - "traefik.http.routers.bentopdf-https.service=bentopdf"
      - "traefik.http.routers.bentopdf-https.middlewares=anubis@docker"

      - "traefik.http.routers.bentopdf-ts.rule=Host(`pdftools.devserver.ts.net`) || Host(`pdf.devserver.ts.net`) || Host(`bentopdf.devserver.ts.net`) || Host(`pdftools.devserver`) || Host(`pdf.devserver`) || Host(`bentopdf.devserver`)"
      - "headnscale.subdomain=pdftools|pdf|bentopdf"
      - "traefik.http.routers.bentopdf-ts.entrypoints=web"
      - "traefik.http.routers.bentopdf-ts.service=bentopdf"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_net

  autokuma:
    image: busybox:latest
    container_name: bentopdf-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.bentopdf_grp.group.name=BentoPDF"
      - 'kuma.bentopdf_grp.group.notification_name_list=["ntfy"]'
      - "kuma.bentopdf_http_1.http.name=BentoPDF (pdftools.pranaovs.me)"
      - "kuma.bentopdf_http_1.http.url=https://pdftools.pranaovs.me"
      - "kuma.bentopdf_http_1.http.parent_name=bentopdf_grp"
      - "kuma.bentopdf_http_2.http.name=BentoPDF (pdf.pranaovs.me)"
      - "kuma.bentopdf_http_2.http.url=https://pdf.pranaovs.me"
      - "kuma.bentopdf_http_2.http.parent_name=bentopdf_grp"
      - "kuma.bentopdf_http_3.http.name=BentoPDF (bentopdf.pranaovs.me)"
      - "kuma.bentopdf_http_3.http.url=https://bentopdf.pranaovs.me"
      - "kuma.bentopdf_http_3.http.parent_name=bentopdf_grp"
      - "kuma.bentopdf_container.docker.name=BentoPDF Container"
      - "kuma.bentopdf_container.docker.docker_container=bentopdf"
      - "kuma.bentopdf_container.docker.docker_host_name=local"
      - "kuma.bentopdf_container.docker.parent_name=bentopdf_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik_net:
    external: true
