services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    restart: always
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_US
    labels:
      - "lazytainer.group=stirlingpdf"
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
    network_mode: service:lazytainer
    restart: always

  lazytainer:
    container_name: lazytainer_stirling_pdf
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      VERBOSE: false
    ports:
      - "30085:8080"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    security_opt:
      - label=type:spc_t
    labels:
      # Lazytainer
      - "lazytainer.group.stirlingpdf.ports=8080"
      - "lazytainer.group.stirlingpdf.minPacketThreshold=2"
      - "lazytainer.group.stirlingpdf.inactiveTimeout=900"
      - "lazytainer.group.stirlingpdf.sleepMethod=stop"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.pdftools.rule=Host(`pdftools.pranaovs.me`) || Host(`pdf.pranaovs.me`) || Host(`stirling.pranaovs.me`)"
      - "traefik.http.services.pdftools.loadbalancer.server.port=8080"
      - "traefik.http.routers.pdftools.entrypoints=websecure"
    networks:
      - traefik_net
    restart: always

networks:
  traefik_net:
    external: true
