services:
  web:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    restart: always
    expose:
      - "80"
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=Host(`cyberchef.pranaovs.me`)"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"
      - "traefik.http.routers.cyberchef.entrypoints=websecure"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
