services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    ports:
      - "30093:8080"
    environment:
      MODE: standalone
      IPINFO_APIKEY: "${SPEEDTEST_IPINFO_APIKEY}"
      DISTANCE: "km"
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-https.rule=Host(`speedtest.pranaovs.me`) || Host(`speed.pranaovs.me`)"
      - "traefik.http.routers.speedtest-https.entrypoints=websecure"
      - "traefik.http.routers.speedtest-https.tls=true"
      - "traefik.http.routers.speedtest-https.tls.certresolver=le"
      - "traefik.http.routers.speedtest-https.service=speedtest"

      - "traefik.http.routers.speedtest-ts.rule=Host(`speedtest.devserver.ts.net`) || Host(`speed.devserver.ts.net`) || Host(`speedtest.devserver`) || Host(`speed.devserver`)"
      - "headnscale.subdomain=speedtest|photos"
      - "traefik.http.routers.speedtest-ts.entrypoints=web"
      - "traefik.http.routers.speedtest-ts.service=speedtest"

      - "traefik.http.services.speedtest.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
      # AutoKuma (uptime-kuma)
      - "kuma.speedtest_grp.group.name=Speedtest"
      - "kuma.speedtest_http_1.http.name=Speedtest (speedtest.pranaovs.me)"
      - "kuma.speedtest_http_1.http.url=https://speedtest.pranaovs.me"
      - "kuma.speedtest_http_1.http.parent_name=speedtest_grp"
      - "kuma.speedtest_http_2.http.name=Speedtest (speed.pranaovs.me)"
      - "kuma.speedtest_http_2.http.url=https://speed.pranaovs.me"
      - "kuma.speedtest_http_2.http.parent_name=speedtest_grp"
      - "kuma.speedtest_container.docker.name=Speedtest Container"
      - "kuma.speedtest_container.docker.docker_container=speedtest"
      - "kuma.speedtest_container.docker.docker_host_name=local"
      - "kuma.speedtest_container.docker.parent_name=speedtest_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
