services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443/tcp # HTTPS entryPoints
      - 30080:8080 # Dashboard WebGui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/traefik.yml:ro
      - letsencrypt:/letsencrypt
    networks:
      - traefik_net
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.traefik_grp.group.name=Traefik"
      - "kuma.traefik_container.docker.name=Traefik Container"
      - "kuma.traefik_container.docker.docker_container=traefik"
      - "kuma.traefik_container.docker.docker_host_name=local"
      - "kuma.traefik_container.docker.parent_name=traefik_grp"

volumes:
  letsencrypt:
    name: letsencrypt

networks:
  traefik_net:
    external: true
