services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443/tcp # HTTPS entryPoints
      - 30080:8080 # Dashboard WebGui
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro # Docker socket
      - ./config/traefik/traefik.yml:/traefik.yml:ro,Z,U
      - letsencrypt:/letsencrypt
      - logs:/var/log/traefik # For crowdsec
    networks:
      - traefik_net
    command:
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"

    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ts.rule=Host(`devserver.ts.net`) || Host(`traefik.devserver.ts.net`) || Host(`devserver`) || Host(`traefik.devserver`)"
      - "headnscale.subdomain=traefik"
      - "traefik.http.routers.traefik-ts.entrypoints=web"
      - "traefik.http.routers.traefik-ts.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
      # Crowdsec
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecappsecenabled=false"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdseclapikey=${CROWDSEC_LAPI_KEY}"
      # Anubis
      - traefik.http.middlewares.anubis.forwardauth.address=http://anubis:8080/.within.website/x/cmd/anubis/api/check

  traefik-dashboard:
    image: hhftechnology/traefik-log-dashboard:latest
    container_name: traefik-log-dashboard
    restart: always
    expose:
      - "5000"
    volumes:
      - ./data/log-dashboard/dashboard:/app/data:Z,U
      - ./data/log-dashboard/geoip:/geoip:ro,z
      - ./data/log-dashboard/positions:/data:Z,U
    environment:
      - AGENT_API_URL=http://traefik-agent:5000
      - AGENT_API_TOKEN=${TRAEFIK_LOG_DASHBOARD_AUTH_TOKEN}
      - AGENT_NAME=Local

      # Node Environment
      - NODE_ENV=production
      - PORT=3000
      - GEOIP_DB_PATH=/geoip/GeoLite2-City.mmdb

      # Display Configuration
      - NEXT_PUBLIC_SHOW_DEMO_PAGE=true
      - NEXT_PUBLIC_MAX_LOGS_DISPLAY=500
    depends_on:
      traefik-agent:
        condition: service_healthy
    networks:
      - traefik_net
      - traefik_logs_net

    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-log-ts.rule=Host(`logs.devserver.ts.net`) || Host(`logs.devserver`)"
      - "headnscale.subdomain=logs"
      - "traefik.http.routers.traefik-log-ts.entrypoints=web"
      - "traefik.http.routers.traefik-log-ts.service=traefik-dashboard"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_net"

  traefik-agent:
    image: hhftechnology/traefik-log-dashboard-agent:latest
    container_name: traefik-log-dashboard-agent
    restart: always
    expose:
      - "5000"
    volumes:
      - logs:/var/log/traefik:ro
      - ./data/log-dashboard/geoip:/geoip:ro,z
      - ./data/log-dashboard/positions:/data:Z,U
    environment:
      # Log Paths
      - TRAEFIK_LOG_DASHBOARD_ACCESS_PATH=/var/log/traefik/access.log
      - TRAEFIK_LOG_DASHBOARD_ERROR_PATH=/var/log/traefik/access.log
      # Authentication
      - TRAEFIK_LOG_DASHBOARD_AUTH_TOKEN=${TRAEFIK_LOG_DASHBOARD_AUTH_TOKEN}
      # System Monitoring
      - TRAEFIK_LOG_DASHBOARD_SYSTEM_MONITORING=true
      # Server Port
      - PORT=5000
      # Geoip
      - TRAEFIK_LOG_DASHBOARD_GEOIP_ENABLED=true
      - TRAEFIK_LOG_DASHBOARD_GEOIP_CITY_DB=/geoip/GeoLite2-City.mmdb
      - TRAEFIK_LOG_DASHBOARD_GEOIP_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/api/logs/status",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - traefik
    networks:
      - traefik_logs_net
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate:latest
    container_name: geoipupdate
    restart: always
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168
    volumes:
      - ./data/log-dashboard/geoip:/usr/share/GeoIP:z,U
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: always
    expose:
      - "8080"
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK: ${CROWDSEC_LAPI_KEY}"
    networks:
      - traefik_net
    depends_on:
      - traefik
    volumes:
      - ./data/crowdsec/:/etc/crowdsec:Z,U
      - logs:/var/log/traefik:ro
      - crowdsec-data:/var/lib/crowdsec/data/
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  anubis:
    image: ghcr.io/techarohq/anubis:main
    container_name: anubis
    expose:
      - "8080"
    volumes:
      - ./config/anubis/anubis.yaml:/policy.yaml:ro,Z,U
    environment:
      - BIND=:8080
      # Telling Anubis to do redirect â€” ensure there is a space after '='
      - "TARGET= "
      - REDIRECT_DOMAINS=*.pranaovs.me,*.deepanalve.dev
      - PUBLIC_URL=https://anubis.pranaovs.me
      - COOKIE_DOMAIN=pranaovs.me
      - POLICY_FNAME=/policy.yaml
    networks:
      - traefik_net

    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.anubis-https.rule=Host(`anubis.pranaovs.me`)
      - traefik.http.routers.anubis-https.entrypoints=websecure
      - traefik.http.routers.anubis-https.service=anubis

      - traefik.http.services.anubis.loadbalancer.server.port=8080
      - traefik.docker.network=traefik_net

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    networks:
      - traefik_net
    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.whoami-https.rule=Host(`whoami.pranaovs.me`)
      - traefik.http.routers.whoami-https.entrypoints=websecure
      - traefik.http.routers.whoami-https.middlewares=anubis@docker
      - traefik.http.routers.whoami-https.service=whoami

      - traefik.http.routers.whoami-ts.rule=Host(`whoami.devserver.ts.net`) || Host(`whoami.devserver.ts.net`)
      - headnscale.subdomain=whoami
      - traefik.http.routers.whoami-ts.entrypoints=web
      - traefik.http.routers.whoami-ts.service=whoami

      - traefik.docker.network=traefik_net
      - traefik.http.services.whoami.loadbalancer.server.port=80

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  autokuma:
    image: busybox:latest
    container_name: traefik-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # Autokuma
      - "kuma.traefik_grp.group.name=Traefik"
      - 'kuma.traefik_grp.group.notification_name_list=["ntfy"]'
      - "kuma.traefik_container.docker.name=Traefik Container"
      - "kuma.traefik_container.docker.docker_container=traefik"
      - "kuma.traefik_container.docker.docker_host_name=local"
      - "kuma.traefik_container.docker.parent_name=traefik_grp"

      - "kuma.crowdsec_container.docker.name=Crowdsec Container"
      - "kuma.crowdsec_container.docker.docker_container=crowdsec"
      - "kuma.crowdsec_container.docker.docker_host_name=local"
      - "kuma.crowdsec_container.docker.parent_name=traefik_grp"

      - "kuma.anubis_container.docker.name=Anubis Container"
      - "kuma.anubis_container.docker.docker_container=anubis"
      - "kuma.anubis_container.docker.docker_host_name=local"
      - "kuma.anubis_container.docker.parent_name=traefik_grp"

      - "kuma.whoami_container.docker.name=whoami Container"
      - "kuma.whoami_container.docker.docker_container=whoami"
      - "kuma.whoami_container.docker.docker_host_name=local"
      - "kuma.whoami_container.docker.parent_name=traefik_grp"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

volumes:
  letsencrypt:
    name: letsencrypt
  logs:
    name: traefik_logs
  crowdsec-data:
  anubis_data:

networks:
  traefik_net:
    external: true
  traefik_logs_net:
