services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443/tcp # HTTPS entryPoints
      - 30080:8080 # Dashboard WebGui
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/traefik.yml:ro
      - letsencrypt:/letsencrypt
      - logs:/var/log/traefik # For crowdsec
    networks:
      - traefik_net
    command:
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"

    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ts.rule=Host(`devserver.ts.net`) || Host(`traefik.devserver.ts.net`) || Host(`devserver`) || Host(`traefik.devserver`)"
      - "headnscale.subdomain=traefik"
      - "traefik.http.routers.traefik-ts.entrypoints=web"
      - "traefik.http.routers.traefik-ts.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
      # Crowdsec
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecappsecenabled=false"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdseclapikey=${CROWDSEC_LAPI_KEY}"
      # Anubis
      - traefik.http.middlewares.anubis.forwardauth.address=http://anubis:8080/.within.website/x/cmd/anubis/api/check

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: always
    expose:
      - "8080"
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK: ${CROWDSEC_LAPI_KEY}"
    networks:
      - traefik_net
    depends_on:
      - traefik
    volumes:
      - ./config/crowdsec/:/etc/crowdsec
      - logs:/var/log/traefik:ro
      - crowdsec-data:/var/lib/crowdsec/data/
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

  anubis:
    image: ghcr.io/techarohq/anubis:main
    container_name: anubis
    expose:
      - "8080"
    volumes:
      - ./anubis.yaml:/policy.yaml
    environment:
      - BIND=:8080
      # Telling Anubis to do redirect â€” ensure there is a space after '='
      - "TARGET= "
      - REDIRECT_DOMAINS=*.pranaovs.me,*.deepanalve.dev
      - PUBLIC_URL=https://anubis.pranaovs.me
      - COOKIE_DOMAIN=pranaovs.me
      - POLICY_FNAME=/policy.yaml
    networks:
      - traefik_net

    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.anubis-https.rule=Host(`anubis.pranaovs.me`)
      - traefik.http.routers.anubis-https.entrypoints=websecure
      - traefik.http.routers.anubis-https.service=anubis

      - traefik.http.services.anubis.loadbalancer.server.port=8080
      - traefik.docker.network=traefik_net

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    networks:
      - traefik_net
    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.whoami-https.rule=Host(`whoami.pranaovs.me`)
      - traefik.http.routers.whoami-https.entrypoints=websecure
      - traefik.http.routers.whoami-https.middlewares=anubis@docker
      - traefik.http.routers.whoami-https.service=whoami

      - traefik.http.routers.whoami-ts.rule=Host(`whoami.devserver.ts.net`) || Host(`whoami.devserver.ts.net`)
      - headnscale.subdomain=whoami
      - traefik.http.routers.whoami-ts.entrypoints=web
      - traefik.http.routers.whoami-ts.service=whoami

      - traefik.docker.network=traefik_net
      - traefik.http.services.whoami.loadbalancer.server.port=80

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

  autokuma:
    image: busybox:latest
    container_name: traefik-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # Autokuma
      - "kuma.traefik_grp.group.name=Traefik"
      - 'kuma.traefik_grp.group.notification_name_list=["ntfy"]'
      - "kuma.traefik_container.docker.name=Traefik Container"
      - "kuma.traefik_container.docker.docker_container=traefik"
      - "kuma.traefik_container.docker.docker_host_name=local"
      - "kuma.traefik_container.docker.parent_name=traefik_grp"

      - "kuma.crowdsec_container.docker.name=Crowdsec Container"
      - "kuma.crowdsec_container.docker.docker_container=crowdsec"
      - "kuma.crowdsec_container.docker.docker_host_name=local"
      - "kuma.crowdsec_container.docker.parent_name=traefik_grp"

      - "kuma.anubis_container.docker.name=Anubis Container"
      - "kuma.anubis_container.docker.docker_container=anubis"
      - "kuma.anubis_container.docker.docker_host_name=local"
      - "kuma.anubis_container.docker.parent_name=traefik_grp"

      - "kuma.whoami_container.docker.name=whoami Container"
      - "kuma.whoami_container.docker.docker_container=whoami"
      - "kuma.whoami_container.docker.docker_host_name=local"
      - "kuma.whoami_container.docker.parent_name=traefik_grp"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  letsencrypt:
    name: letsencrypt
  logs:
    name: traefik_logs
  crowdsec-data:
  anubis_data:

networks:
  traefik_net:
    external: true
