services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443/tcp # HTTPS entryPoints
      - 30080:8080 # Dashboard WebGui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/traefik.yml:ro
      - letsencrypt:/letsencrypt
    networks:
      - traefik_net
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.traefik_grp.group.name=Traefik"
      - "kuma.traefik_container.docker.name=Traefik Container"
      - "kuma.traefik_container.docker.docker_container=traefik"
      - "kuma.traefik_container.docker.docker_host_name=local"
      - "kuma.traefik_container.docker.parent_name=traefik_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ts.rule=Host(`devserver.ts.net`) || Host(`traefik.devserver.ts.net`) || Host(`devserver`) || Host(`traefik.devserver`)"
      - "headnscale.subdomain=traefik"
      - "traefik.http.routers.traefik-ts.entrypoints=web"
      - "traefik.http.routers.traefik-ts.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"

    command:
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"

volumes:
  letsencrypt:
    name: letsencrypt

networks:
  traefik_net:
    external: true
