services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443/tcp # HTTPS entryPoints
      - 30080:8080 # Dashboard WebGui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/traefik.yml:ro
      - letsencrypt:/letsencrypt
      - logs:/var/log/traefik # For crowdsec
    networks:
      - traefik_net
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.traefik_grp.group.name=Traefik"
      - "kuma.traefik_container.docker.name=Traefik Container"
      - "kuma.traefik_container.docker.docker_container=traefik"
      - "kuma.traefik_container.docker.docker_host_name=local"
      - "kuma.traefik_container.docker.parent_name=traefik_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ts.rule=Host(`devserver.ts.net`) || Host(`traefik.devserver.ts.net`) || Host(`devserver`) || Host(`traefik.devserver`)"
      - "headnscale.subdomain=traefik"
      - "traefik.http.routers.traefik-ts.entrypoints=web"
      - "traefik.http.routers.traefik-ts.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
      # Crowdsec
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecappsecenabled=false"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdseclapikey=${CROWDSEC_LAPI_KEY}"

    command:
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: always
    expose:
      - "8080"
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK: ${CROWDSEC_LAPI_KEY}"

    volumes:
      - ./config:/etc/crowdsec
      - logs:/var/log/traefik:ro
      - crowdsec-data:/var/lib/crowdsec/data/
    labels:
      # Autokuma
      - "kuma.traefik_container.docker.name=Crowdsec Container"
      - "kuma.traefik_container.docker.docker_container=crowdsec"
      - "kuma.traefik_container.docker.docker_host_name=local"
      - "kuma.traefik_container.docker.parent_name=traefik_grp"

    networks:
      - traefik_net

volumes:
  letsencrypt:
    name: letsencrypt
  logs:
    name: traefik_logs
  crowdsec-data:

networks:
  traefik_net:
    external: true
