services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    command: --cleanup --label-enable --interval 3600
    security_opt:
      - label=type:spc_t
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

  autokuma:
    image: busybox:latest
    container_name: watchtower-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.watchtower_grp.group.name=Watchtower"
      - 'kuma.watchtower_grp.group.notification_name_list=["ntfy"]'
      - "kuma.watchtower_container.docker.name=Watchtower Container"
      - "kuma.watchtower_container.docker.docker_container=watchtower"
      - "kuma.watchtower_container.docker.docker_host_name=local"
      - "kuma.watchtower_container.docker.parent_name=watchtower_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
