services:
  aperisolve-web:
    image: ghcr.io/zeecka/aperisolve:latest
    #build: .
    container_name: aperisolve-web
    restart: always
    volumes:
      - apresults:/app/aperisolve/results
    depends_on:
      postgres:
        condition: service_healthy
      initdb:
        condition: service_completed_successfully
      redis:
        condition: service_started
      worker:
        condition: service_started
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "true"]

    labels:
      # Traefik
      - "traefik.http.routers.aperisolve-ts.rule=Host(`aperisolve.devserver.ts.net`) || Host(`aperisolve.devserver`)"
      - "headnscale.subdomain=aperisolve"
      - "traefik.http.routers.aperisolve-ts.entrypoints=web"
      - "traefik.http.routers.aperisolve-ts.service=aperisolve-web"

      - "traefik.http.services.aperisolve-web.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik_net"
    networks:
      - default
      - traefik_net

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: aperisolve-anubis
    restart: always
    expose:
      - "8923"
    environment:
      BIND: ":8923"
      SLOG_LEVEL: "WARN"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://aperisolve-web:5000"
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      COOKIE_DOMAIN: pranaovs.me
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    volumes:
      - ../traefik/config/anubis/anubis.yaml:/data/cfg/botPolicy.yaml:ro,z

    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.aperisolve-https.rule=Host(`aperisolve.pranaovs.me`)"
      - "traefik.http.routers.aperisolve-https.entrypoints=websecure"
      - "traefik.http.routers.aperisolve-https.service=aperisolve-anubis"

      - "traefik.http.services.aperisolve-anubis.loadbalancer.server.port=8923"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

    networks:
      - traefik_net

  worker:
    image: ghcr.io/zeecka/aperisolve:latest
    #build: .
    container_name: aperisolve-worker
    restart: unless-stopped
    command: rq worker default --url redis://redis:6379/0
    volumes:
      - apresults:/app/aperisolve/results
    depends_on:
      postgres:
        condition: service_healthy
      initdb:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - default

  initdb:
    image: ghcr.io/zeecka/aperisolve:latest
    #build: .
    container_name: aperisolve-initdb
    command: python -m aperisolve.utils.init_db
    volumes:
      - apresults:/app/aperisolve/results
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"
    networks:
      - default

  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aperiuser -d aperisolve"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - default

  redis:
    image: redis:7
    container_name: redis
    restart: always
    env_file:
      - .env
    networks:
      - default

  rqdashboard:
    image: eoranged/rq-dashboard
    container_name: rq-dashboard
    restart: always
    ports:
      - "9181:9181"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - default

volumes:
  apresults:
  pgdata:

networks:
  traefik_net:
    external: true
