services:
  radicale:
    image: ghcr.io/kozea/radicale:latest
    user: root
    ports:
      - "30089:5232"
    volumes:
      - ./config:/etc/radicale:ro
      - ./data:/var/lib/radicale
    restart: always
