services:
  radicale:
    image: ghcr.io/kozea/radicale:latest
    user: root
    container_name: radicale
    ports:
      - "30089:5232"
    volumes:
      - ./config:/etc/radicale:ro,Z,U
      - ./data:/var/lib/radicale:Z,U
    restart: always
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.radicale-ts.rule=Host(`radicale.devserver.ts.net`) || Host(`caldav.devserver.ts.net`) || Host(`carddav.devserver.ts.net`) || Host(`contacts.devserver.ts.net`) || Host(`calendar.devserver.ts.net`) || Host(`radicale.devserver`) || Host(`caldav.devserver`) || Host(`carddav.devserver`) || Host(`contacts.devserver`) || Host(`calendar.devserver`)"
      - "headnscale.subdomain=radicale|caldav|carddav|contacts|calendar"
      - "traefik.http.routers.radicale-ts.entrypoints=web"
      - "traefik.http.routers.radicale-ts.service=radicale"
      - "traefik.http.services.radicale.loadbalancer.server.port=5232"
      - "traefik.docker.network=traefik_net"

    networks:
      - traefik_net

  autokuma:
    image: busybox:latest
    container_name: radicale-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.radicale_grp.group.name=Radicale"
      - 'kuma.radicale_grp.group.notification_name_list=["ntfy"]'
      - "kuma.radicale_container.docker.name=Radicale Container"
      - "kuma.radicale_container.docker.docker_container=radicale"
      - "kuma.radicale_container.docker.docker_host_name=local"
      - "kuma.radicale_container.docker.parent_name=radicale_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

networks:
  traefik_net:
    external: true
