services:
  radicale:
    image: ghcr.io/kozea/radicale:latest
    user: root
    container_name: radicale
    ports:
      - "30089:5232"
    volumes:
      - ./config:/etc/radicale:ro
      - ./data:/var/lib/radicale
    restart: always
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.radicale_grp.group.name=Radicale"
      - "kuma.radicale_container.docker.name=Radicale Container"
      - "kuma.radicale_container.docker.docker_container=radicale"
      - "kuma.radicale_container.docker.docker_host_name=local"
      - "kuma.radicale_container.docker.parent_name=radicale_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
