global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "service_discovery"
    file_sd_configs:
      - files:
          - /prometheus-docker-sd/docker-targets.json
    static_configs:
      - targets: ["immich-server:8082"]
