services:
  headscale:
    image: docker.io/headscale/headscale:stable
    restart: always
    container_name: headscale
    ports:
      - "3478:3478/udp"
    volumes:
      - ./config/headscale:/etc/headscale
      - ./lib/headscale:/var/lib/headscale
      - ./dns:/dns
      - headscale_run:/var/run/headscale
    command: serve
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`headscale.pranaovs.me`)"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "me.tale.headplane.target=headscale"

    networks:
      - traefik_net

  headplane:
    image: ghcr.io/tale/headplane:latest
    container_name: headplane
    restart: always
    depends_on:
      - headscale
    expose:
      - "3000"
    security_opt:
      - label=type:spc_t
    volumes:
      - ./config/headplane/:/etc/headplane
      - ./lib/headplane:/var/lib/headplane
      - ./config/headscale:/etc/headscale
      - ./private:/private:ro
      - ./dns:/dns
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.headplane-ts.rule=Host(`headplane.devserver.ts.net`)"
      - "headnscale.subdomain=headplane"
      - "traefik.http.routers.headplane-ts.entrypoints=web"
      - "traefik.http.routers.headplane-ts.service=headplane"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_net"

    networks:
      - traefik_net

  headnscale:
    image: ghcr.io/pranaovs/headnscale:latest
    container_name: headnscale
    depends_on:
      - headscale
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dns:/data
    expose:
      - "8080"
    environment:
      - HEADNSCALE_JSON_PATH=/data/extra_records.json
      - HEADNSCALE_HOSTS_PATH=/data/hosts.txt
      - HEADNSCALE_NODE_HOSTNAME=devserver
      - HEADNSCALE_NODE_IP=100.64.0.2
      - HEADNSCALE_NODE_IP6=fd7a:115c:a1e0::2
      - HEADNSCALE_NO_BASE_DOMAIN=true
    security_opt:
      - label=type:spc_t
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.headnscale-ts.rule=(Host(`devserver.ts.net`) || Host(`devserver`)) && (Path(`/hosts`) || Path(`/hosts.txt`))"
      - "headnscale.subdomain=traefik"
      - "traefik.http.routers.headnscale-ts.entrypoints=web"
      - "traefik.http.routers.headnscale-ts.priority=1000"
      - "traefik.http.routers.headnscale-ts.service=headnscale"
      - "traefik.http.services.headnscale.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"

    networks:
      - traefik_net

  autokuma:
    image: busybox:latest
    container_name: headscale-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.headscale_grp.group.name=Headscale"
      - 'kuma.headscale_grp.group.notification_name_list=["ntfy"]'
      - "kuma.headscale_http.http.name=Headscale HTTP"
      - "kuma.headscale_http.http.url=https://headscale.pranaovs.me/health"
      - "kuma.headscale_http.http.parent_name=headscale_grp"
      - "kuma.headscale_container.docker.name=Headscale Container"
      - "kuma.headscale_container.docker.docker_container=headscale"
      - "kuma.headscale_container.docker.docker_host_name=local"
      - "kuma.headscale_container.docker.parent_name=headscale_grp"

      - "kuma.headplane_container.docker.name=Headplane Container"
      - "kuma.headplane_container.docker.docker_container=headplane"
      - "kuma.headplane_container.docker.docker_host_name=local"
      - "kuma.headplane_container.docker.parent_name=headscale_grp"

      - "kuma.headnscale_container.docker.name=Headnscale Container"
      - "kuma.headnscale_container.docker.docker_container=headnscale"
      - "kuma.headnscale_container.docker.docker_host_name=local"
      - "kuma.headnscale_container.docker.parent_name=headscale_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  headscale_run:

networks:
  traefik_net:
    external: true
