services:
  headscale:
    image: docker.io/headscale/headscale:stable
    restart: always
    container_name: headscale
    ports:
      - "3478:3478/udp"
    volumes:
      - ./config:/etc/headscale
      - ./lib:/var/lib/headscale
      - ./dns:/dns
      - headscale_run:/var/run/headscale
    command: serve
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`headscale.pranaovs.me`)"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls=true"
      - "traefik.http.routers.headscale.tls.certresolver=le"
      # AutoKuma (uptime-kuma)
      - "kuma.headscale_grp.group.name=Headscale"
      - "kuma.headscale_http.http.name=Headscale HTTP"
      - "kuma.headscale_http.http.url=https://headscale.pranaovs.me/health"
      - "kuma.headscale_http.http.parent_name=headscale_grp"
      - "kuma.headscale_container.docker.name=Headscale Container"
      - "kuma.headscale_container.docker.docker_container=headscale"
      - "kuma.headscale_container.docker.docker_host_name=local"
      - "kuma.headscale_container.docker.parent_name=headscale_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_net

  headnscale:
    image: ghcr.io/pranaovs/headnscale:latest
    container_name: headnscale
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dns:/data
    environment:
      - HEADNSCALE_JSON_PATH=/data/extra_records.json
      - HEADNSCALE_NODE_HOSTNAME=devserver
      - HEADNSCALE_NODE_IP=100.64.0.2
      - HEADNSCALE_NODE_IP6=fd7a:115c:a1e0::2
      - HEADNSCALE_NO_BASE_DOMAIN=true
    security_opt:
      - label=type:spc_t

volumes:
  headscale_run:

networks:
  traefik_net:
    external: true
