services:
  blog:
    container_name: blog
    image: ghcr.io/pranaovs/blog:latest
    expose:
      - "80"
    restart: always
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.blog-https.rule=Host(`blog.pranaovs.me`)"
      - "traefik.http.routers.blog-https.entrypoints=websecure"
      - "traefik.http.routers.blog-https.service=blog"
      - "traefik.http.routers.blog-https.middlewares=anubis@docker"

      - "traefik.http.routers.blog-ts.rule=Host(`blog.devserver.ts.net`) || Host(`blog.devserver`)"
      - "headnscale.subdomain=blog"
      - "traefik.http.routers.blog-ts.entrypoints=web"
      - "traefik.http.routers.blog-ts.service=blog"

      - "traefik.http.services.blog.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
