services:
  blog:
    container_name: blog
    image: ghcr.io/pranaovs/blog:latest
    expose:
      - "80"
    restart: always
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.blog-https.rule=Host(`blog.pranaovs.me`)"
      - "traefik.http.routers.blog-https.entrypoints=websecure"
      - "traefik.http.routers.blog-https.service=blog"
      - "traefik.http.routers.blog-https.middlewares=anubis@docker"

      - "traefik.http.routers.blog-ts.rule=Host(`blog.devserver.ts.net`) || Host(`blog.devserver`)"
      - "headnscale.subdomain=blog"
      - "traefik.http.routers.blog-ts.entrypoints=web"
      - "traefik.http.routers.blog-ts.service=blog"

      - "traefik.http.services.blog.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
    networks:
      - traefik_net

  autokuma:
    image: busybox:latest
    container_name: blog-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.blog_grp.group.name=Blog"
      - 'kuma.blog_grp.group.notification_name_list=["ntfy"]'
      - "kuma.blog_http_1.http.name=Blog (blog.pranaovs.me)"
      - "kuma.blog_http_1.http.url=https://blog.pranaovs.me"
      - "kuma.blog_http_1.http.parent_name=blog_grp"
      - "kuma.blog_container.docker.name=Blog Container"
      - "kuma.blog_container.docker.docker_container=blog"
      - "kuma.blog_container.docker.docker_host_name=local"
      - "kuma.blog_container.docker.parent_name=blog_grp"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

networks:
  traefik_net:
    external: true
