services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: always
    ports:
      - "30084:3000"
    environment:
      ENVIRONMENT: "prod"
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD: ${WAKAPI_DB_PASSWORD}
      WAKAPI_PASSWORD_SALT: ${WAKAPI_PASSWORD_SALT}
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      WAKAPI_PUBLIC_URL: "https://wakapi.pranaovs.me"
      WAKAPI_LEADERBOARD_REQUIRE_AUTH: true
      WAKAPI_WARM_CACHES: false
      WAKAPI_INSECURE_COOKIES: true
      WAKAPI_ALLOW_SIGNUP: false
      WAKAPI_DISABLE_FRONTPAGE: true
    env_file: ".env"
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.wakapi.rule=Host(`wakapi.pranaovs.me`) || Host(`wakatime.pranaovs.me`)"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.services.wakapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.wakapi.entrypoints=websecure"
      - "traefik.http.routers.wakapi.tls=true"
      - "traefik.http.routers.wakapi.tls.certresolver=le"
      # AutoKuma (uptime-kuma)
      - "kuma.wakapi_grp.group.name=Wakapi"
      - "kuma.wakapi_http_1.http.name=Wakapi (wakapi.pranaovs.me)"
      - "kuma.wakapi_http_1.http.url=https://wakapi.pranaovs.me"
      - "kuma.wakapi_http_1.http.parent_name=wakapi_grp"
      - "kuma.wakapi_http_2.http.name=Wakapi (wakatime.pranaovs.me)"
      - "kuma.wakapi_http_2.http.url=https://wakatime.pranaovs.me"
      - "kuma.wakapi_http_2.http.parent_name=wakapi_grp"
      - "kuma.wakapi_container.docker.name=Wakapi Container"
      - "kuma.wakapi_container.docker.docker_container=wakapi-wakapi-1"
      - "kuma.wakapi_container.docker.docker_host_name=local"
      - "kuma.wakapi_container.docker.parent_name=wakapi_grp"
    networks:
      - default
      - traefik_net

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_DB: "wakapi"
      POSTGRES_PASSWORD: ${WAKAPI_DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.wakapi_db_container.docker.name=Wakapi Database"
      - "kuma.wakapi_db_container.docker.docker_container=wakapi-db-1"
      - "kuma.wakapi_db_container.docker.docker_host_name=local"
      - "kuma.wakapi_db_container.docker.parent_name=wakapi_grp"

networks:
  traefik_net:
    external: true
