services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii
    restart: always
    volumes:
      - ./data/upload:/var/www/html/storage/upload:Z,U
    env_file: .env
    ports:
      - 30086:8080
    depends_on:
      - db
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-ts.rule=Host(`firefly.devserver.ts.net`) || Host(`expenses.devserver.ts.net`) || Host(`firefly.devserver`) || Host(`expenses.devserver`)"
      - "headnscale.subdomain=firefly|expenses"
      - "traefik.http.routers.firefly-ts.entrypoints=web"
      - "traefik.http.routers.firefly-ts.service=firefly"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
    networks:
      - traefik_net
      - default

  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    volumes:
      - ./data/db:/var/lib/mysql:Z,U
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    depends_on:
      - app
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

  autokuma:
    image: busybox:latest
    container_name: firefly_iii-autokuma
    restart: always
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD", "sleep", "0"]
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.firefly_grp.group.name=Firefly III"
      - 'kuma.firefly_grp.group.notification_name_list=["ntfy"]'
      - "kuma.firefly_container.docker.name=Firefly III Container"
      - "kuma.firefly_container.docker.docker_container=firefly_iii"
      - "kuma.firefly_container.docker.docker_host_name=local"
      - "kuma.firefly_container.docker.parent_name=firefly_grp"

      - "kuma.firefly_db_container.docker.name=Firefly III Database Container"
      - "kuma.firefly_db_container.docker.docker_container=firefly_iii_db"
      - "kuma.firefly_db_container.docker.docker_host_name=local"
      - "kuma.firefly_db_container.docker.parent_name=firefly_grp"

      - "kuma.firefly_cron_container.docker.name=Firefly III Cron Container"
      - "kuma.firefly_cron_container.docker.docker_container=firefly_iii_cron"
      - "kuma.firefly_cron_container.docker.docker_host_name=local"
      - "kuma.firefly_cron_container.docker.parent_name=firefly_grp"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"

networks:
  traefik_net:
    external: true
