services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii
    restart: always
    volumes:
      - ./data/upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 30086:8080
    depends_on:
      - db
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.firefly_grp.group.name=Firefly III"
      - "kuma.firefly_container.docker.name=Firefly III App"
      - "kuma.firefly_container.docker.docker_container=firefly_iii"
      - "kuma.firefly_container.docker.docker_host_name=local"
      - "kuma.firefly_container.docker.parent_name=firefly_grp"
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    volumes:
      - ./data/db:/var/lib/mysql
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.firefly_db_container.docker.name=Firefly III Database"
      - "kuma.firefly_db_container.docker.docker_container=firefly_iii_db"
      - "kuma.firefly_db_container.docker.docker_host_name=local"
      - "kuma.firefly_db_container.docker.parent_name=firefly_grp"
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    depends_on:
      - app
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.firefly_cron_container.docker.name=Firefly III Cron"
      - "kuma.firefly_cron_container.docker.docker_container=firefly_iii_cron"
      - "kuma.firefly_cron_container.docker.docker_host_name=local"
      - "kuma.firefly_cron_container.docker.parent_name=firefly_grp"
