services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root
    volumes:
      - ./config/prometheus:/etc/prometheus:ro
      - ./data/prometheus:/prometheus
      - prometheus-docker-sd:/prometheus-docker-sd:ro
    ports:
      - "30091:9090"
    networks:
      - metrics_net
    depends_on:
      - prometheus-docker-sd

  prometheus-docker-sd:
    image: "stucky/prometheus-docker-sd:latest"
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - prometheus-docker-sd:/prometheus-docker-sd:rw

volumes:
  prometheus-docker-sd:

networks:
  metrics_net:
    external: true
