services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root
    volumes:
      - ./config/prometheus:/etc/prometheus:ro
      - ./data/prometheus:/prometheus
      - prometheus-docker-sd:/prometheus-docker-sd:ro
    ports:
      - "30091:9090"
    networks:
      - metrics_net
    depends_on:
      - prometheus-docker-sd
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.metrics_grp.group.name=Metrics"
      - "kuma.prometheus_container.docker.name=Prometheus Container"
      - "kuma.prometheus_container.docker.docker_container=prometheus"
      - "kuma.prometheus_container.docker.docker_host_name=local"
      - "kuma.prometheus_container.docker.parent_name=metrics_grp"

  prometheus-docker-sd:
    image: "stucky/prometheus-docker-sd:latest"
    container_name: prometheus_docker_sd
    restart: always
    security_opt:
      - no-new-privileges:true
      - label=type:spc_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - prometheus-docker-sd:/prometheus-docker-sd:rw
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.metrics_grp.group.name=Metrics"
      - "kuma.prometheus_docker_sd_container.docker.name=Prometheus Docker SD Container"
      - "kuma.prometheus_docker_sd_container.docker.docker_container=prometheus_docker_sd"
      - "kuma.prometheus_docker_sd_container.docker.docker_host_name=local"
      - "kuma.prometheus_docker_sd_container.docker.parent_name=metrics_grp"

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - "30092:3000"
    user: root
    volumes:
      - "./data/grafana:/var/lib/grafana"
      # - "./config/grafana:/etc/grafana"
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.metrics_grp.group.name=Metrics"
      - "kuma.grafana_container.docker.name=Grafana Container"
      - "kuma.grafana_container.docker.docker_container=grafana"
      - "kuma.grafana_container.docker.docker_host_name=local"
      - "kuma.grafana_container.docker.parent_name=metrics_grp"
    networks:
      - metrics_net

volumes:
  prometheus-docker-sd:

networks:
  metrics_net:
    external: true
